- name: backend
  hosts: backend
  become: yes
  tasks:
  - name:  disable
    ansible.builtin.command: dnf module disable nodejs -y
  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y
  - name: insall node js
    ansible.builtin.dnf: #onlyworks for redhat family
      name: nodejs
      state: installed
  - name: add user expense
    ansible.builtin.user:
      name: expense
  - name: create directory
    ansible.builtin.file:
      path: /app
      state: directory
       