- name: frontend server
  hosts: frontend
  become: ye
  tasks:
  - name: nginx install
    ansible.builtin.dnf:
      name: nginx
      state: installed
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  - name: remve default html file
    ansile.builtin.file:
      path: /usr/share/nginx/html/*
      state: absent
  - name: download zip
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

  - name: unzip
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes